name: 自由與開源軟體中文化計畫
name_en: The Free and Open Source Software Localization Project

description: 藉由專業翻譯課程參與、技術工作坊與社群實習曝光，打破既往軟體中文化後版本更新乏人問津的窘境，亦納入與數位發展部合作５項專案：GOV.UK Notify、GOV.UK Forms、Element（Matrix Client）、IRMA、Standard for Public Code。
description_en: "The project aims to break the previous situation where there was little interest in updating software localization. This is accomplished through participation in professional translation courses, technical workshops, and exposure to the community. The project has also collaborated with the Digital Development Department on five projects: GOV.UK Notify, GOV.UK Forms, Element (Matrix Client), IRMA, and the Standard for Public Code."

tagline: 
tagline_en: 

og_image: /p/oss_localization/cover.jpg
og_image_en: /en/p/civicsense/covereng.png
header_image: /p/oss_localization/banner.jpg
header_image_en: /p/oss_localization/banner.jpg
avatar_image: /p/oss_localization/cover.jpg
avatar_image_en: /en/p/civicsense/covereng.png
theme_color: 

start: 
end: 

topic_ids:
  - source
field_ids:
  - it
  - community
  - misc
tags:
tags_en:

links:
  - title: 數位部中文化成果
    url: https://github.com/moda-gov-tw
    color: green
    icon: github icon
links_en:
  - title: The result on Moda's Github
    url: https://github.com/moda-gov-tw
    color: green
    icon: world icon

organizer_ids:
  - ocf
co-organizer_ids:
board_ids:
staff_ids:
  - singing
  - rosa

listed: yes
listed_en: yes
