name: 網路自由小聚
name_en: coffee and circumvention
description: 在國際夥伴 Internet Freedom Festival 社群的建議之下，OCF 和來自「摩茲台灣社群Mozilla TW」、 「COSCUP」、和「公民團體資安暨隱私交流 CSCS (Cyber Shield Civil Society)」的夥伴一起發起了每月固定的網路自由小聚。
description_en: The idea of the meetup came from the Internet Freedom Festival (IFF), one of the largest digital rights communities in the world. It gathers hackers from all over the world to defend activists oin the frontline. OCF was invited by IFF to initiate  “Coffee & Circumvention” (C&C) in Taiwan
og_image: 
header_image: /p/issues/issues-cover.png
avatar_image: 
links:
links_en:
actions:
  - title: 活動共筆
    url: https://hackmd.io/efBMZl4ITImkxUOjlmByHg?view
    icon: cloud
    color: green
organizer_ids:
listed: yes
listed_en: yes
reports:
  yyyy: mm
