name: OpenChain 臺灣社群
name_en: OpenChain Taiwan Working Group

description: OpenChain 專案隸屬於 Linux Foundation Project，透過簡化及標準化開源合規實務，協助產業在碰觸或思索開源合規 (Open Source Compliance) 爭議或政策時，可更為有效滿足開源合規，從而建立產業供應鏈對開源軟體的信任。包含微軟、Google、高通、西門子、Sony 與 Uber 等都已採用OpenChain 進行開源合規管理並通過 OpenChain 認證。
description_en: 
abbr: openchain
abbr_en: openchain

tagline: openchain
tagline_en: 

og_image: /p/openchain/openchain.jpg
header_image:
avatar_image: 
theme_color: 

start: 
end: 


topic_ids:
  - source
field_ids:
  - legal
tags:
  - 定期活動
tags_en:


actions: 
  - title: 
    url: 
    color: 
    icon: 
    
organizer_ids:
  - openchain
co-organizer_ids:
  -
coordinator_id:
  -
board_ids:
  -bob
staff_ids: 
  -rosa

listed: yes
listed_en: 
