# 這個檔案用來存一些影響到全站的設定

current: 2025
# 這個欄位用來設定網站當前年度，影響範圍包括
# 1.專案頁：判斷此專案是否為當年度，如果不是的話會
#   a.在專案名稱後面刮號加註年度
#   b.不顯示 call to action 按鈕
# 2.活動頁：判斷此活動是否為當年度，如果不是的話會
#   a.在活動名稱後面刮號加註年度
# 3.首頁：進行中專案卡片的資料來自哪個年份
# 4.重新導向的頁面中 year 設定為 current 者
years:
  - "2025"
  - "2024"
  - "2023"
  - "2022"
  - "2021"
  - "2020"
  - "2019"
  - "2018"
  - "2017"
  - "2016"
  - "2015"
  - "2014"

menu:
  # 這個欄位用來設定主選單的選項與連結
  - title: 關於
    url: /about/
  - title: 夥伴
    url: /people/
  - title: 基金會專案
    url: /p/ocf
  - title: 社群夥伴
    url: /p/community
  - title: 活動
    url: /journal/
  - title: 電子報
    url: /news/
  - title: 捐款徵信
    url: https://blog.ocf.tw/search/label/捐款徵信
  - title: OCFLab
    url: https://lab.ocf.tw/
  - title: 支持我們
    url: /supportus/

menu_en:
  - title: About
    url: /en/p/what_is_ocf_en.html
  - title: Our Projects
    url: /en/p/ocf
  - title: Community Partners
    url: /en/p/community
