# 2020 版專案資料範本

name: Gcoin 區塊鏈計畫
# 專案的中文正式名稱，會顯示在專案列表頁、專案頁、活動頁
name_en: Gcoin Blockchain Project
# 英文版網頁用

description: 開放文化基金會下之 Gcoin 專案，除致力於 Gcoin 軟體程式之研發，也希望有興趣的開發者一同參與，群策群力讓這個開源專案快速成長，對台灣的金融界能及時貢獻。專案成果除將以開放原始碼授權外，並將推廣新一代的數位金融基礎建設概念及尋求相關法制商業模式等配套落實，使台灣成為 Gcoin 技術能實際應用的場域。

og_image: /p/gcoin/2019/cover.png
# og_image: url
# 專案的預覽縮圖，會出現在專案列表頁、sns 連結預覽
# 選用長寬比接近 facebook og image 的圖片（1200 x 630）
header_image: /p/gcoin/2019/cover_bg.png
# header_image: url
# 專案頁首的底圖，若有，會出現在專案頁、活動頁
# 選用長寬比接近長條形的圖片（1400 x 300）
avatar_image: /p/gcoin/2019/avatar.png
# avatar_image: url
# 專案的 avatar 圖檔網址，若有，會出現在專案頁的左側邊欄
# 選用長寬比接近正方形的圖片
theme_color: teal
    

topic_ids:
  - source
field_ids:
  - finance
tags_en:

organizer_ids:
  - gcoin
co-organizer_ids:
  - ocf
staff_ids: 
  - rock

actions: 
  - title: 捐款贊助
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=22
    color: green
    icon: dollar
  - title: 加入開發
    url: https://github.com/OpenNetworking/gcoin-community
    color: blue
    icon: github
  - title: 如果你想捐贈儀器設備，請與我們聯絡 ( hi@ocf.tw)。

listed: yes
listed_en: 
