name: Civic Sense
name_en: Civic Sense 

description: 提升公民與環保意識！從臺灣跨出國際，幫全球社群蒐集當地環境監測資料
description_en: From Taiwan to the whole world, let’s help communities get the data they need to monitor their changing environment. When communities have access to sensors, it’s “civic sense”. 
  

tagline: 
tagline_en: 

og_image: /p/civicsense/civicsensecover1.png
og_image_en: /en/p/civicsense/civicsensecover1.png
header_image: /p/civicsense/civicsensebanner1
header_image_en: /p/civicsense/civicsensebanner1
avatar_image: /p/civicsense/civicsensecover1.png
avatar_image_en: /en/p/civicsense/civicsensecover1.png
theme_color: 

start: 
end: 

topic_ids:
  - misc
  - overseas
field_ids:
  -  it
tags:
tags_en:

links:
  - title: 點此觀看第一場網路研討會影片
    url: https://www.youtube.com/playlist?list=PLFuYOsppHDrl4pPE0VsHmAOXiZXMx7O43
    color: green
    icon: world icon
  - title: 點此觀看研討會共同筆記與問答
    url: https://hackmd.io/@en5bBuSOSvKdMhZUCaoFyQ/rk_whtKXt
    color: yellow
    icon: world icon
links_en:
  - title: Watch the playlist from our first webinar
    url: https://www.youtube.com/playlist?list=PLFuYOsppHDrl4pPE0VsHmAOXiZXMx7O43
    color: green
    icon: world icon
  - title: Check out the notes from the Q&A here
    url: https://hackmd.io/@en5bBuSOSvKdMhZUCaoFyQ/rk_whtKXt
    color: yellow
    icon: world icon
  - title: September/October Monthly Update
    url: https://drive.google.com/file/d/1Knz-aOShyYvHBpkGPURTAlTPPThplNi_/preview
    color: green
    icon: world icon 
  - title: November Monthly Update
    url: https://drive.google.com/file/d/1j_RCvHYrP9_xDovmVpuMHtTA3OPSZaDR/view?usp=sharing
    color: green
    icon: world icon 
  - title: December Monthly Update
    url: https://drive.google.com/file/d/1jVGCO8R0GkdHQzt670IW8HCgF-WafKXK/view?usp=sharing
    color: green
    icon: world icon 
  - title: January Monthly Update
    url: https://drive.google.com/file/d/1yoT2pICkccmhMbK2D9ZCJUV_6wuxUsTc/view?usp=sharing
    color: green
    icon: world icon
  - title: February Monthly Update
    url: https://drive.google.com/file/d/1PefFFPK64GaVckxWmAea0QuK7Z4UqC5Q/view?usp=sharing
    color: green
    icon: world icon 
  - title: March/April Monthly Update
    url: https://drive.google.com/file/d/1ZGOCcYP_UZDSY1A756F0ndpIIaPxe-5q/view?usp=sharing
    color: green
    icon: world icon 
  - title: July Monthly Update
    url: https://drive.google.com/file/d/1ae4JrxABzpd1xwfHrc_L8o4kbfgf9cS3/view?usp=sharing
    color: green
    icon: world icon 

organizer_ids:
  - ocf
co-organizer_ids:
board_ids:
  - pofeng
staff_ids: 
  - singing
  - Leaf
  - Sam 

listed: yes
listed_en: yes
