name: PyCourse
name_en: PyCourse

description: Python 是頂尖的美國大學用來教授入門程式設計課程的第一選擇；天瓏書局 2017 年暢銷書排行榜，前十名中有八本是跟 Python 相關的書；在 KDnuggets 的調查中，Python 已經超越 R 成為數據科學和機器學習最多人使用的語言。
description_en: 

abbr: PyCourse
abbr_en: PyCourse

tagline: 
tagline_en: 

og_image: /p/pycourse/2019/og.png
header_image: /p/pycourse/2019/og.png
avatar_image: /p/pycourse/2019/og.png
theme_color: 

start: 
end: 


topic_ids:
  - source

field_ids:
  - education

tags:
  - 定期活動
tags_en:


organizer_ids:
  - pycourse
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
  - pofeng

staff_ids:
  - rock

listed: 
listed_en: 

reports:
