# 2020 版專案資料範本

name: 中文資訊處理開源基礎建設
# 專案的中文正式名稱，會顯示在專案列表頁、專案頁、活動頁
name_en: Chewing IM
# 英文版網頁用

description: 中文資訊處理包含訊息、顯示、輸入、處理等領域，主要有翻譯、字型、輸入法、語言資料處理等項目，近幾年來自由開源系統的中文環境雖有許多改善，但仍存在不少問題。我們希望能改善相關軟體的基本翻譯、增進中文輸入的堪用度、提升軟體中文支援程度等，並會舉辦相關活動，吸引大眾關注中文資訊處理的發展，並產生興趣進而投資時間或人力。 

og_image: /p/chewingim/og.png
# og_image: url
# 專案的預覽縮圖，會出現在專案列表頁、sns 連結預覽
# 選用長寬比接近 facebook og image 的圖片（1200 x 630）
header_image: 
# header_image: url
# 專案頁首的底圖，若有，會出現在專案頁、活動頁
# 選用長寬比接近長條形的圖片（1400 x 300）
avatar_image: /p/chewingim/og.png
# avatar_image: url
# 專案的 avatar 圖檔網址，若有，會出現在專案頁的左側邊欄
# 選用長寬比接近正方形的圖片
theme_color: teal
links:
  - title: 贊助社群
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=25
topic_ids:
  - source
field_ids:
  - it
tags_en:

organizer_ids:
  - chewingim
co-organizer_ids:
  - ocf
staff_ids: 
  - rock

listed: yes
listed_en: 
