name: 國際會議獎助計畫
name_en: Support Program for International Conference Participation

description: <b>不知道怎麼參與國際會議？ 快跟著「獎助計畫」找到支援和資源！！</b>數位時代的我們，每天接受大量的新資訊、新技術，快速上手的同時卻常常不知何去何從，不只臺灣的我們困擾，國際各方各國也都有同樣問題，而面對各類開放原始碼、開放科技、數位人權、網路自由的議題，國際上有各式各樣的會議，這些國際會議不只討論現況、危機、解方，更是認識夥伴，一起結盟、合作專案、探索國際職涯的好地方。         
description_en: Taiwan-based open source and open culture contributors have continued to impress global communities with outstanding projects, such as the "Instant Mask Map," in the past few years. In the hope of empowering local communities and enhancing international engagements, the program support local contributor to participate in open culture-related international conferences.

tagline: 帶你用開源走向國際
tagline_en: 

og_image: /p/intldonate/head_new_intldonate.png
header_image: /p/intldonate/head_new_intldonate.png
avatar_image: 
theme_color: blue
organizer_ids: ocf
start: 
end: 

type_ids:
topic_ids:
field_ids:
  - it
tags:
tags_en:

listed: yes
listed_en: yes


links:
  - title: OCF 國際會議獎助計畫 - FOSDEM 2024 報名至 11/30
    url: https://docs.google.com/forms/d/e/1FAIpQLSftSumqthsElUUMRBh3oyrA3LQ99TPfnn8xWVVU3lma3-9kLw/viewform
    icon: 



