
name: 子專案名稱（必填）
name_en: Project name

description: 用一段話簡單介紹這個專案（必填）
description_en: Introduce the project in one paragraph

abbr: text
abbr_en: text

tagline: text
tagline_en: text

og_image: /p/project_id/cover.png
og_image_en: /p/project_id/cover_en.png

header_image: /p/project_id/header.png
header_image_en: /p/project_id/header_en.png

avatar_image: /p/project_id/avatar.png
avatar_image_en: /p/project_id/avatar_en.png

theme_color: teal

start: yyyy/mm/dd
end: yyyy/mm/dd

type_ids:
  - id
topic_ids:
  - id
field_ids:
  - id
tags:
  - text
tags_en:
  - text

metas:
  - label: text
    content: text
metas_en:
  - label: text
    content: text

links:
  - title: text
    url: url
    icon: (semantic ui icon)
links_en:
  - title: text
    url: url
    icon: (semantic ui icon)

actions:
  - title: text
    url: url
    icon: (semantic ui icon)
    color: text
  - title: text
actions_en: 
  - title: text
    url: url
    icon: (semantic ui icon)
    color: text
  - title: text

advisor_ids:
  - id
organizer_ids:
  - id
co-organizer_ids:
  - id
implementer_ids:
  - id
sponsor_ids:
  - id

coordinator_ids:
  - id
case-handler_ids:
  - id
co-worker_ids:
  - id
consultant_ids:
  - id
volunteer_ids:
  - id
contributor_ids:
  - id
donors:
  - text
donors_en:
  - text

board_ids:
  - id
staff_ids:
  - id

listed: 
listed_en: 

reports:
  yyyy: mm
