name: CC Taiwan Chapter
name_en: CC Taiwan Chapter

description: Creative Commons 是美國的非營利組織提出的公眾授權條款，台灣稱為「創用 CC」授權條款，是現今網路世代身為一個創作者所不可或缺的開放共享的授權方式。開放文化基金會自 2018 年起，參與 Creative Commons 會員，持續與 CC 組織互動，並協助社群 "CC Taiwan Chapter" 自主發展，繼續深化公眾授權知識的分享與傳播之外，也讓 CC 授權推廣的種子，能接觸更多國內外的自由文化社群。 
description_en: Creative Commons is a global network connecting practitioners who adhere to the free culture ideal and use the various open content licenses. 

abbr: 
abbr_en: 

tagline: 
tagline_en: 

og_image: /p/cctw/CCTW-Logo-2024.png
header_image: /p/cctw/2018/cc-cover-cc0.jpg
avatar_image: /p/cctw/CCTW-Logo-2024.png
theme_color: 

start: 2016/
end: 


topic_ids:
  - data
  - license
field_ids:
  - legal
tags:
tags_en:

metas:
metas_en:

links:
  - title: CC 社群網站
    url: https://cc.ocf.tw/
    icon: home
    color: grey
  - title: CC 相關資源
    url: https://cc.ocf.tw/resource
    icon: cloud
    color: grey
  - title: CC 教學影片
    url: https://www.youtube.com/watch?list=PLFuYOsppHDrlGNj8Ardp1ELYlvEC5jk9o&v=9fuajCuCV4g
    icon: file video
    color: grey
  - title: CC 論壇
    url: https://groups.google.com/forum/#!forum/cctw-discussion
    icon: comments
    color: grey
  - title: Facebook
    url: https://www.facebook.com/CCTaiwan/
    icon: facebook
    color: grey
links_en:

actions:
  - title: 邀請演講申請
    url: https://goo.gl/forms/Uo9EP4GHNnbnLlBt2
    icon: microphone
    color: grey
  - title: 參與社群簡單自介
    url: mailto:cc@ocf.tw
    icon: users
    color: grey
actions_en:

advisor_ids:
organizer_ids:
  - cctw
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
  - lucien
  - rock
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
  - pofeng
staff_ids:
  - singing
  - rock

listed: yes
listed_en: yes

reports:
