name:  公共出資，公共程式 Public Money, Public Code
name_en: 公共出資，公共程式 Public Money, Public Code
 

description: 公共程式：以開放原始碼推動政府數位化，實現公共資源共享與創新。
description_en: 公共程式：以開放原始碼推動政府數位化，實現公共資源共享與創新。


tagline:  
tagline_en: 

og_image: /p/pmpc/class/PMPC_Class.png
og_image_en: 
header_image: /p/pmpc/class/PMPC_banner.png
avatar_image: /p/pmpc/class/PMPC_Class.png
theme_color: purple

start: 
end: 

topic_ids:
  - tech
  - source
  - data
  - government
field_ids:
  - it
  - rsh
  - adv
tags:
tags_en:

links:
  - title: PMPC 公共程式培力系列試辦課程
    url: https://ocf.tw/p/pmpc/class/
    color: purple
    icon: world icon 

links_en:
  - title: 
    url: 
    color: 
    icon: 

organizer_ids:
    - ocf
co-organizer_ids:
consultant_ids:

board_ids:

staff_ids:


listed: yes
listed_en: no
