name:  公共出資，公共程式 Public Money, Public Code
name_en: 公共出資，公共程式 Public Money, Public Code
 

description: 公共程式（Public Code）是政府數位化服務中採用的開放原始碼軟體，以及政府開發並以開放原始碼方式釋出的軟體。其特色包括允許重複利用、避免廠商壟斷、促進民眾參與協作和確保內容開放透明。本系列課程旨在提升公務人員對公共程式的認知與認同，向大眾推廣公共程式概念，並增強我國運用集體智慧進行社會創新的能力。課程由數位發展部主辦，勤業眾信聯合會計師事務所及財團法人開放文化基金會共同執行。通過這些培力課程，我們期望能夠賦能政府公務人員，提升公共程式的實務應用能力，並普及公共程式概念。加入我們，一同探索公共程式的無限可能！
description_en: 公共程式（Public Code）是政府數位化服務中採用的開放原始碼軟體，以及政府開發並以開放原始碼方式釋出的軟體。其特色包括允許重複利用、避免廠商壟斷、促進民眾參與協作和確保內容開放透明。本系列課程旨在提升公務人員對公共程式的認知與認同，向大眾推廣公共程式概念，並增強我國運用集體智慧進行社會創新的能力。課程由數位發展部主辦，勤業眾信聯合會計師事務所及財團法人開放文化基金會共同執行。通過這些培力課程，我們期望能夠賦能政府公務人員，提升公共程式的實務應用能力，並普及公共程式概念。加入我們，一同探索公共程式的無限可能！


tagline:  
tagline_en: 

og_image: /p/pmpc/class/PMPC_Class.png
og_image_en: 
header_image: /p/pmpc/class/PMPC_banner.png
avatar_image: /p/pmpc/class/PMPC_Class.png
theme_color: purple

start: 
end: 

topic_ids:
  - tech
  - source
  - data
  - government
field_ids:
  - it
  - rsh
  - adv
tags:
tags_en:

links:
  - title: PMPC 公共程式培力系列試辦課程
    url: https://ocf.tw/p/pmpc/class/
    color: purple
    icon: world icon 

links_en:
  - title: 
    url: 
    color: 
    icon: 

organizer_ids:
    - ocf
co-organizer_ids:
consultant_ids:

board_ids:

staff_ids:


listed: yes
listed_en: no
