# 2020 版專案資料範本

name: OpenStreetMap Taiwan
# 專案的中文正式名稱，會顯示在專案列表頁、專案頁、活動頁
name_en: OpenStreetMap Taiwan
# 英文版網頁用

description: 開放街圖（OpenStreetMap，簡稱 OSM）是一個靠群眾協作而成的地理資料庫，同時也是採用開放資料授權的全球地圖，由像你一樣的使用者繪製，在日常生活、導航、學術、商業領域創造出豐富的應用，台灣開放街圖社群是活躍的參與者之一。凡支持開放街圖運動之個人，捐款至開放文化基金會下之台灣開放街圖社群專戶，即可加入台灣開放街圖社群會員，參與社群營運之事務。

og_image: /p/osmtw/og.jpg
# og_image: url
# 專案的預覽縮圖，會出現在專案列表頁、sns 連結預覽
# 選用長寬比接近 facebook og image 的圖片（1200 x 630）
header_image: /p/osmtw/cover.jpg
# header_image: url
# 專案頁首的底圖，若有，會出現在專案頁、活動頁
# 選用長寬比接近長條形的圖片（1400 x 300）
avatar_image: /p/osmtw/avatar.png
# avatar_image: url
# 專案的 avatar 圖檔網址，若有，會出現在專案頁的左側邊欄
# 選用長寬比接近正方形的圖片
theme_color: teal
    
links:
  - title: 贊助社群
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=16
topic_ids:
  - data
field_ids:
  - geo
tags:
  - 定期活動
tags_en:

organizer_ids:
  - osmtw
co-organizer_ids:
  - ocf
staff_ids: 
  - rosa

listed: yes
listed_en: 
