name: WordCamp Taiwan
name_en: Students’ Information Technology Conference
description: WordCamp 是自 2006 年起源於美國舊金山，在世界各地所舉辦一系列的自發性開放原始碼的 WordPress 使用者實體社群活動。透過一整天內容豐富的大型活動，將來自台灣各地、以及來自國外的 WordPress 愛好者齊聚一堂，分享知識、交流經驗，並共同學習最新的科技變革與技術資訊。
description_en:
abbr: WordCamp 
abbr_en: WordCamp
tagline: WordCamp

og_image: /p/wordcamp/wordcamp2023.jpg
header_image: /p/wordcamp/Banner.jpg
avatar_image: /p/wordcamp/wordcamp2023.jpg
theme_color: 
start: 
end: 
tags:
  - 大型研討會
  - 定期活動
topic_ids:
  - source
field_ids:
  - 
organizer_ids:
  - wordcamp
board_ids:
  - 
staff_ids:
  - leaf

listed: yes
listed_en: 

actions: 

