name: 開放農業實驗基地
name_en: Open Hack Farm

description: 進行農耕生活四年多，於 2017 年，在宜蘭的小農村裡，成立了「開放農業實驗基地」。希望聚集更多小農與科技人，透過社群的力量，進行開放農耕實驗及研發，並運用適切科技輔助，打造更友善的農食環境。讓我們與生活產生新的連結吧，Open Hack Farm！
description_en: 

abbr: 
abbr_en: 

tagline: 
tagline_en: 

og_image: /p/openhackfarm/2019/og.jpg
header_image: 
avatar_image: 
theme_color: 

start: 
end: 


topic_ids:
  - data
field_ids:
  - agri
tags:
tags_en:

metas:
  - label: 
    content: 
metas_en:

links:
links_en:

actions: 
# 專案頁的 call to action，可以是按鈕或一段文字，會出現在左側邊欄的最下方
  - title: 贊助專案
    # 按鈕上的文字
    url: https://ocf.neticrm.tw/civicrm/contribute/transact?reset=1&id=32
    # 按下後會連去哪裡
    color: green
    # 按鈕顏色，可使用任一 semantic ui 的顏色，參考： http://semantic-ui.com/elements/button.html#colored
    icon: world icon
    # 按鈕文字前的 icon，可使用任一 semantic ui 的 icon，參考： http://semantic-ui.com/elements/icon.html
  - title: 參與專案 / 贊助設備
    # 按鈕上的文字
    url: https://www.facebook.com/groups/OpenHackFarm/
    # 按下後會連去哪裡
    color: blue
    # 按鈕顏色，可使用任一 semantic ui 的顏色，參考： http://semantic-ui.com/elements/button.html#colored
    icon: facebook
    # 按鈕文字前的 icon，可使用任一 semantic 
actions_en:

advisor_ids:
organizer_ids:
  - farm
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:
case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
  - jimmy
staff_ids:
  - leona

listed: yes
listed_en: 

reports:
  2020: 01
