name: SITCON 學生計算機年會
name_en: Students’ Information Technology Conference
description: 2012 年中，一群學生在社群浪潮中為相同的理想聚集，秉持「以學生為本、由學生自發舉辦」的核心理念，SITCON 學生計算機年會及同名社群自 2013 年起，陸續舉行年會、定期聚、黑客松、工作坊、夏令營與多場演講，於技術交流之餘，亦在推廣資訊及開源教育上不遺餘力，希望透過技術與知識的激盪，給予學生們一個用自身力量實踐夢想的舞台。
description_en:
abbr: SITCON 
abbr_en: SITCON
tagline: SITCON

og_image: /p/sitcon/sitcon2024.png
header_image: /p/sitcon/sitcon2024.png
avatar_image: /p/sitcon/sitcon2024.png
theme_color: 
start: 
end: 
tags:
  - 大型研討會
  - 定期活動


topic_ids:
  - source
field_ids:
  - education
organizer_ids:
  - sitcon
board_ids:
  - pofeng
staff_ids:
  - rock

listed: yes
listed_en: 

actions: 
# 專案頁的 call to action，可以是按鈕或一段文字，會出現在左側邊欄的最下方
#  - title: SITCON 夏令營官網
    # 按鈕上的文字
#    url: http://sitcon.camp/2017/
    # 按下後會連去哪裡
#    color: green
    # 按鈕顏色，可使用任一 semantic ui 的顏色，參考： http://semantic-ui.com/elements/button.html#colored
#    icon: world icon
    # 按鈕文字前的 icon，可使用任一 semantic ui 的 icon，參考： http://semantic-ui.com/elements/icon.html
  - title: SITCON 學生計算機年會
    # 按鈕上的文字
    url: https://sitcon.org/2020/
    # 按下後會連去哪裡
    color: green
    # 按鈕顏色，可使用任一 semantic ui 的顏色，參考： http://semantic-ui.com/elements/button.html#colored
    icon: world icon
    # 按鈕文字前的 icon，可使用任一 semantic ui 的 icon，參考： http://semantic-ui.com/elements/icon.html
  - title: SITCON 粉絲專頁
    # 按鈕上的文字
    url: https://www.facebook.com/SITCONtw
    # 按下後會連去哪裡
    color: blue
    # 按鈕顏色，可使用任一 semantic ui 的顏色，參考： http://semantic-ui.com/elements/button.html#colored
    icon: facebook
    # 按鈕文字前的 icon，可使用任一 semantic ui 的 icon，參考： http://semantic-ui.com/elements/icon.html
