name:  RightsCon 全球數位人權大會 2025
name_en: RightsCon 2025

description: RightsCon 2025 將於 2 月 24 日至 27 日在臺北！全球數位人權大會（RightsCon），由國際非營利組織 Access Now 主辦，是全球最大的數位人權會議。2025 年不僅首度在東亞舉辦，更選擇臺北作為據點，預計將有來自 150 個國家、約 3,000 名產官學專家親身到訪臺灣，用 18 軌 500+ 場議程，討論人工智慧、數位治理、開源應用於公民倡議、反數位壓迫等議題。是臺灣開源技術社群、人權組織一覽全球數位人權議題的大好機會！
description_en: RightsCon 2025 will be held in Taipei, the world's largest digital human rights conference, is organized by the international non-profit organization Access Now.

tagline:  
tagline_en: 

og_image: /p/rightscon2025/RightsCon2025.png
og_image_en: /p/rightscon2025/RightsCon2025.png
header_image: /assets/images/shell-bg05.png
avatar_image: /p/rightscon2025/RightsCon2025.png
theme_color: purple

start: 2025/
end: 

topic_ids:
  - tech
  - dr
field_ids:
  - it
  - rsh
  - adv
  - legal
tags:
tags_en:

links:
  - title: 【票】優惠票申請中
    url: https://ocf.tw/p/rightscon2025/#coupon
    color: purple
    icon: world icon
  - title: 【主題】現場有哪些議題？
    url: https://ocf.tw/p/rightscon2025/#topics
    color: purple
    icon: world icon
  - title: 【OCF】我們在現場的活動有哪些？
    url: https://ocf.tw/p/rightscon2025/#ocf-at-rc25
    color: purple
    icon: world icon
links_en:
  - title: Find OCF at RightsCon
    url: https://ocf.tw/en/p/rightscon2025/#ocf-at-rc25
    color: purple
    icon: world icon
    
actions: 
  - title: 【活動】周邊活動大全
    url: https://ocf.tw/p/rightscon2025/#side-events
    color: blue
    icon: beer
  - title: 【議程】大會與台灣相關之議程大全
    url: https://ocf.tw/p/rightscon2025/#tw-sessions
    icon: users
    color: purple
actions_en: 
  - title: Side Events at Taipei
    url: https://ocf.tw/en/p/rightscon2025/#side-events
    color: blue
    icon: beer
  - title: RC Sessions about Taiwan
    url: https://ocf.tw/en/p/rightscon2025/#tw-sessions
    icon: users
    color: purple

organizer_ids:
  - accessnow
co-organizer_ids: 
  - ocf
consultant_ids:

board_ids:

staff_ids:

listed: yes
listed_en: yes
